name: Deploy to environment

on:
  push:
    branches:
      - main
    paths:
      - 'bin/*'
      - 'support/*'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

env:
  IMAGE_NAME: rsd-utilities

jobs:
  set-env:
    name: Set environment variables
    runs-on: ubuntu-24.04
    outputs:
      github_repository_lc: ${{ steps.var.outputs.github_repository_lc }}
      environment: ${{ steps.var.outputs.environment }}
    steps:
      - id: var
        run: |
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          GITHUB_REPOSITORY=${{ github.repository }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "github_repository_lc=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ${{ needs.set-env.outputs.environment }}
    runs-on: ubuntu-24.04
    needs: [ set-env ]
    environment: ${{ needs.set-env.outputs.environment }}
    permissions:
      packages: write
      id-token: write
      attestations: write
    steps:
      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/build@v5.2.1
        with:
          build-args: CI=true
          image-name: ${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DFE-Digital/deploy-azure-container-apps-action/.github/actions/import@v5.2.1
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-acr-client-id: ${{ secrets.ACR_CLIENT_ID }}
          azure-acr-name: ${{ secrets.ACR_NAME }}
          image-name: ${{ env.IMAGE_NAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID || '' }}
          AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION_ID || '' }}
          AZURE_ACR_CLIENT_ID: ${{ secrets.ACR_CLIENT_ID || '' }}

      - name: Login with OIDC
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.ACI_CLIENT_ID }}

      - name: Restart Container
        uses: azure/cli@v2
        with:
          inlineScript: |
            az container start \
              --name ${{ secrets.CONTAINER_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }}
